In [24]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [25]:
data= pd.read_csv('~/code/dmassonfr/Spotify_hit_predictor/raw_data/final_dataset_3.csv')

/tmp/ipykernel_3001/2764810032.py:1: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  data= pd.read_csv('~/code/dmassonfr/Spotify_hit_predictor/raw_data/final_dataset_3.csv')

In [26]:
data.head()

,id,name,popularity,duration_ms,explicit,artists,release_date,danceability,energy,key,...,instrumentalness,liveness,valence,tempo,id_artists,followers,genres,artist_popularity,preview_url,cover_album
0,35iwgR4jXetI318WEWsa1Q,Carve,6,126903,0,Uli,1922-02-22,0.645,0.44500,0,...,0.744,0.1510,0.127,104.851,45tIt06XoI0Iio4LBEVpls,91.0,NaN,4,NaN,NaN
1,0PH9AACae1f957JAavhOl2,Lazy Boi,0,157333,0,Uli,1922-02-22,0.298,0.46000,1,...,0.856,0.4360,0.402,87.921,45tIt06XoI0Iio4LBEVpls,91.0,NaN,4,NaN,NaN
2,2SiNuAZ6jIU9xhClRKXcST,Sketch,0,87040,0,Uli,1922-02-22,0.634,0.00399,5,...,0.919,0.1050,0.396,79.895,45tIt06XoI0Iio4LBEVpls,91.0,NaN,4,NaN,NaN
3,4vV7uBcF2AnjNTOejBS5oL,L'enfer,0,40000,0,Uli,1922-02-22,0.657,0.32500,10,...,0.856,0.0931,0.105,81.944,45tIt06XoI0Iio4LBEVpls,91.0,NaN,4,NaN,NaN
4,598LlBn6jpEpVbLjmZPsYV,Graphite,0,104400,0,Uli,1922-02-22,0.644,0.68400,7,...,0.802,0.0847,0.138,100.031,45tIt06XoI0Iio4LBEVpls,91.0,NaN,4,NaN,NaN

In [27]:
data['release_year'] = [int(i.split('-')[0]) for i in data['release_date']]

In [28]:
dataset= data.drop(columns=['id', 'duration_ms', 'explicit','danceability','energy','key','instrumentalness','liveness','valence','tempo','id_artists','followers','genres','artist_popularity','loudness','mode','speechiness','acousticness','preview_url','cover_album','release_date'])

In [29]:
dataset.head()

       name  popularity artists  release_year
0     Carve           6     Uli          1922
1  Lazy Boi           0     Uli          1922
2    Sketch           0     Uli          1922
3   L'enfer           0     Uli          1922
4  Graphite           0     Uli          1922

In [30]:
dataset= dataset[dataset['release_year']==2023]

In [31]:
dataset= dataset.sort_values('popularity')

In [32]:
dataset[dataset['popularity']<10].head(20)

,name,popularity,artists,release_year
444670,charlie,0,icymi,2023
445976,What Do You Call It?,0,Beth McCarthy,2023
446560,running shoes,0,nicole han,2023
446561,robot boy,0,jenny nuo,2023
445969,Rodeo,0,Bimini,2023
446562,If I Weren't Me,0,Katherine Li,2023
445329,Grapevines,0,Rozie Ramati,2023
444950,Rouages,0,Vincent Cucheval,2023
444638,complicated_5,0,artistbasm,2023
445324,Fighting Myself,0,Linkin Park,2023
447186,Declan Rice,0,Odumodublvck,2023
445800,Void,0,Kaleem Taylor,2023
445996,PSYCHOPARTY,0,"Hey, Baby",2023
445983,Hands - Edit,0,Elkka,2023
445782,ลูกเทวดา,0,SPRITE,2023
445771,อาบน้ำตา,0,YourMOOD,2023
445988,And He Never Was The Same Again,0,Kele,2023
447206,same zmartwienia,0,Kuban,2023
446660,"Hey, Mickey!",0,Baby Tate,2023
446652,AIN'T GONNA ANSWER,0,NLE Choppa,2023

In [33]:
artist =['The Weeknd','Miley Cyrus','Bizarrap','Peso Pluma','Quevedo','Udo Lindenberg','Naiara Azevedo','Headie One','Paramore','French The Kid','Fredo','Irina Rimes','Tzanca Uraganu','Momma','Club Sport','Island of Love','VILLFORTH','Cristina Hart','Baby Jeweler','Osole','oomool']
track = ['Die For You - Remix','Flowers','Shakira: Bzrp Music Sessions, Vol. 53', 'PRC','VISTA AL MAR','Komet','Palhaça -Ao vivo','Martin\'s Sofa','This Is Why','Single Player','Dave Flow','Neiubita ta','Alo baza baza','Bang Bang','Songs About It','Grow','Strangely Attracted','Crash','5am Thoughts','Don\'t be sad','Whitening']
popularity= [95,100,97,92,82,83,81,71,73,63,63,52,57,46,45,35,36,25,28,15,14]
pred=[92.2,82.5,88.7,88.8,79.3,78.8,79.3,69.7,73,64,62.8,50.2,56.7,45.6,48.6,34.9,31.4,26.8,24.4,15,14.7]

In [34]:
df = pd.DataFrame (artist, columns = ['artist'])

In [35]:
df.shape

(21, 1)

In [36]:
df['track']=track

In [37]:
df['popularity']=popularity

In [38]:
df['prediction']=pred

In [39]:
df.sort_values('popularity',ascending=False)

,artist,track,popularity,prediction
1,Miley Cyrus,Flowers,100,82.5
2,Bizarrap,"Shakira: Bzrp Music Sessions, Vol. 53",97,88.7
0,The Weeknd,Die For You - Remix,95,92.2
3,Peso Pluma,PRC,92,88.8
5,Udo Lindenberg,Komet,83,78.8
4,Quevedo,VISTA AL MAR,82,79.3
6,Naiara Azevedo,Palhaça -Ao vivo,81,79.3
8,Paramore,This Is Why,73,73.0
7,Headie One,Martin's Sofa,71,69.7
10,Fredo,Dave Flow,63,62.8
9,French The Kid,Single Player,63,64.0
12,Tzanca Uraganu,Alo baza baza,57,56.7
11,Irina Rimes,Neiubita ta,52,50.2
13,Momma,Bang Bang,46,45.6
14,Club Sport,Songs About It,45,48.6
16,VILLFORTH,Strangely Attracted,36,31.4
15,Island of Love,Grow,35,34.9
18,Baby Jeweler,5am Thoughts,28,24.4
17,Cristina Hart,Crash,25,26.8
19,Osole,Don't be sad,15,15.0
20,oomool,Whitening,14,14.7

In [46]:
df['difference %']=((df['prediction'] - df['popularity'])/  df['popularity'])*100

In [49]:
df['difference %']=abs(df['difference %'].round(2))

In [50]:
df

,artist,track,popularity,prediction,difference %
0,The Weeknd,Die For You - Remix,95,92.2,2.95
1,Miley Cyrus,Flowers,100,82.5,17.50
2,Bizarrap,"Shakira: Bzrp Music Sessions, Vol. 53",97,88.7,8.56
3,Peso Pluma,PRC,92,88.8,3.48
4,Quevedo,VISTA AL MAR,82,79.3,3.29
5,Udo Lindenberg,Komet,83,78.8,5.06
6,Naiara Azevedo,Palhaça -Ao vivo,81,79.3,2.10
7,Headie One,Martin's Sofa,71,69.7,1.83
8,Paramore,This Is Why,73,73.0,0.00
9,French The Kid,Single Player,63,64.0,1.59
10,Fredo,Dave Flow,63,62.8,0.32
11,Irina Rimes,Neiubita ta,52,50.2,3.46
12,Tzanca Uraganu,Alo baza baza,57,56.7,0.53
13,Momma,Bang Bang,46,45.6,0.87
14,Club Sport,Songs About It,45,48.6,8.00
15,Island of Love,Grow,35,34.9,0.29
16,VILLFORTH,Strangely Attracted,36,31.4,12.78
17,Cristina Hart,Crash,25,26.8,7.20
18,Baby Jeweler,5am Thoughts,28,24.4,12.86
19,Osole,Don't be sad,15,15.0,0.00
20,oomool,Whitening,14,14.7,5.00

,artist,track,popularity,prediction,difference %
0,The Weeknd,Die For You - Remix,95,92.2,2.95
1,Miley Cyrus,Flowers,100,82.5,17.50
2,Bizarrap,"Shakira: Bzrp Music Sessions, Vol. 53",97,88.7,8.56
3,Peso Pluma,PRC,92,88.8,3.48
4,Quevedo,VISTA AL MAR,82,79.3,3.29
5,Udo Lindenberg,Komet,83,78.8,5.06
6,Naiara Azevedo,Palhaça -Ao vivo,81,79.3,2.10
7,Headie One,Martin's Sofa,71,69.7,1.83
8,Paramore,This Is Why,73,73.0,0.00
9,French The Kid,Single Player,63,64.0,1.59
10,Fredo,Dave Flow,63,62.8,0.32
11,Irina Rimes,Neiubita ta,52,50.2,3.46
12,Tzanca Uraganu,Alo baza baza,57,56.7,0.53
13,Momma,Bang Bang,46,45.6,0.87
14,Club Sport,Songs About It,45,48.6,8.00
15,Island of Love,Grow,35,34.9,0.29
16,VILLFORTH,Strangely Attracted,36,31.4,12.78
17,Cristina Hart,Crash,25,26.8,7.20
18,Baby Jeweler,5am Thoughts,28,24.4,12.86
19,Osole,Don't be sad,15,15.0,0.00
20,oomool,Whitening,14,14.7,5.00